create extension if not exists pgcrypto;

create table public.friends_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_by uuid not null,
  is_open boolean not null default false,
  invite_token text not null default encode(gen_random_bytes(18), 'hex') unique,
  status text not null default 'approved' check (status in ('pending', 'approved', 'rejected')),
  reviewed_at timestamptz,
  reviewed_by uuid,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index friends_groups_one_owned_group_per_user
  on public.friends_groups (created_by);

create table public.profiles (
  id uuid primary key,
  display_name text,
  avatar_emoji text,
  color_class text,
  favorite_team text,
  default_friends_group_id uuid references public.friends_groups(id) on delete set null,
  last_active_friends_group_id uuid references public.friends_groups(id) on delete set null,
  points integer not null default 0,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.friends_group_users (
  id uuid primary key default gen_random_uuid(),
  friends_group_id uuid not null references public.friends_groups(id) on delete cascade,
  user_id uuid not null,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  unique (friends_group_id, user_id)
);

create table public.friends_group_join_requests (
  id uuid primary key default gen_random_uuid(),
  friends_group_id uuid not null references public.friends_groups(id) on delete cascade,
  user_id uuid not null,
  user_display_name text,
  message text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  requested_at timestamptz not null default now(),
  processed_at timestamptz,
  processed_by uuid,
  unique (friends_group_id, user_id)
);

create table public.football_competitions (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'sportmonks',
  provider_league_id bigint not null,
  name text not null,
  country_name text,
  logo_url text,
  current_provider_season_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_league_id)
);

create table public.football_seasons (
  id uuid primary key default gen_random_uuid(),
  competition_id uuid not null references public.football_competitions(id) on delete cascade,
  provider text not null default 'sportmonks',
  provider_season_id bigint not null,
  name text,
  starts_at date,
  ends_at date,
  is_current boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_season_id),
  unique (competition_id, provider_season_id)
);

create table public.friends_group_subscriptions (
  id uuid primary key default gen_random_uuid(),
  friends_group_id uuid not null references public.friends_groups(id) on delete cascade,
  competition_id uuid not null references public.football_competitions(id) on delete restrict,
  season_id uuid references public.football_seasons(id) on delete set null,
  provider text not null default 'sportmonks',
  provider_league_id bigint not null,
  provider_season_id bigint,
  status text not null default 'pending' check (status in ('pending', 'active', 'paused', 'archived', 'rejected')),
  created_by uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index friends_group_subscriptions_one_active_per_group
  on public.friends_group_subscriptions (friends_group_id)
  where status = 'active';

create table public.fixtures (
  id integer generated by default as identity primary key,
  provider text not null default 'sportmonks',
  sm_fixture_id bigint not null unique,
  sm_league_id bigint not null,
  sm_season_id bigint,
  sm_round_id bigint,
  home_team text not null,
  away_team text not null,
  home_score integer,
  away_score integer,
  live_home_score integer,
  live_away_score integer,
  has_red_card boolean,
  current_minute integer,
  match_date date not null,
  match_time time not null,
  starting_at timestamptz,
  matchweek text,
  status text not null default 'scheduled',
  provider_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index fixtures_competition_schedule_idx
  on public.fixtures (sm_league_id, sm_season_id, match_date, match_time);

create index fixtures_status_schedule_idx
  on public.fixtures (status, match_date, match_time);

create table public.predictions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  fixture_id integer not null references public.fixtures(id) on delete cascade,
  friends_group_id uuid references public.friends_groups(id) on delete cascade,
  home_score_prediction integer not null check (home_score_prediction >= 0),
  away_score_prediction integer not null check (away_score_prediction >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index predictions_user_fixture_group_uidx
  on public.predictions (user_id, fixture_id, friends_group_id)
  where friends_group_id is not null;

create unique index predictions_user_fixture_global_uidx
  on public.predictions (user_id, fixture_id)
  where friends_group_id is null;

create table public.red_card_predictions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  fixture_id integer not null references public.fixtures(id) on delete cascade,
  friends_group_id uuid references public.friends_groups(id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index red_card_predictions_user_fixture_group_uidx
  on public.red_card_predictions (user_id, fixture_id, friends_group_id)
  where friends_group_id is not null;

create unique index red_card_predictions_user_fixture_global_uidx
  on public.red_card_predictions (user_id, fixture_id)
  where friends_group_id is null;

create table public.user_submissions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  friends_group_id uuid not null references public.friends_groups(id) on delete cascade,
  matchweek text not null,
  submitted_at timestamptz not null default now(),
  unique (user_id, friends_group_id, matchweek)
);

create table public.weekly_scores (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  friends_group_id uuid not null references public.friends_groups(id) on delete cascade,
  week_number integer not null,
  fixtures_predicted integer not null default 0,
  exact_score_points integer not null default 0,
  correct_result_points integer not null default 0,
  total_goals_bonus integer not null default 0,
  red_card_bonus integer not null default 0,
  points_earned integer not null default 0,
  group_points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, friends_group_id, week_number)
);

create table public.match_events (
  id uuid primary key default gen_random_uuid(),
  fixture_id integer references public.fixtures(id) on delete cascade,
  provider text not null default 'sportmonks',
  sm_event_id bigint unique,
  sm_fixture_id bigint,
  event_type text not null,
  minute integer not null,
  player_name text not null,
  team text not null,
  assist_player text,
  provider_payload jsonb,
  created_at timestamptz not null default now()
);

create index match_events_fixture_minute_idx
  on public.match_events (fixture_id, minute);

create table public.live_feed_events (
  id uuid primary key default gen_random_uuid(),
  friends_group_id uuid references public.friends_groups(id) on delete cascade,
  fixture_id integer references public.fixtures(id) on delete cascade,
  matchweek text,
  sm_fixture_id bigint,
  event_key text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  ai_message text,
  pushed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (friends_group_id, event_key)
);

create table public.notification_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  friends_group_id uuid references public.friends_groups(id) on delete cascade,
  channel text not null check (channel in ('web_push', 'expo', 'fcm', 'apns')),
  endpoint text not null,
  auth_secret text,
  p256dh_key text,
  device_label text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, channel, endpoint)
);
